name: Live Chat CI/CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache node_modules
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: |
            frontend/node_modules
            backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install and Review Frontend Code
      - name: Install and Review Frontend Code
        run: |
          cd frontend
          npm install
          npx eslint .

      # Install and Review Backend Code
      - name: Install and Review Backend Code
        run: |
          cd backend
          npm install
          npx eslint .

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Deploy Frontend to Vercel
      - name: Deploy Frontend to Vercel
        run: |
          cd frontend
          npm install
          npm run build
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes

      # Deploy Backend to Render
      - name: Deploy Backend to Render
        run: |
          curl -X POST https://api.render.com/v1/services/srv-cs6sm90gph6c73f99p1g/deploys \
          -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}"
